path: ./
jobs: 10
cache: ./phplint.cache
extensions:
  - php
exclude:
  - vendor
  - i18n
  - bin
  - assets
  - docs
  - node_modules
  - wordpress_org_assets
  - tests
warning: false
memory_limit: -1
