name: JavaScript Unit Tests

on:
  push:
    branches:
      - trunk
      - develop
  pull_request:

jobs:
  UnitTests:
    name: JavaScript unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare node
        uses: woocommerce/grow/prepare-node@actions-v1
        with:
          node-version-file: ".nvmrc"

      - name: Run JavaScript unit tests
        run: npm run test:js
